name: build & test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          key: shared
          path: raw.tar
      - if: steps.cache.outputs.cache-hit != 'true'
        run: make raw.tar
      - name: build & install
        run: |
          sudo apt-get update -q
          sudo apt-get install -yq ripgrep
          make scan-c scan-go scan-rs

      - run: make c.txt
      - run: make go.txt
      - run: make rs.txt
      - run: make grep.txt
        if: github.event_name != 'pull_request'
      - run: make ripgrep.txt
      - run: make js.txt
      - name: summarize
        run: |
          make times.md
          {
            printf "## Best Times\n\n"
            cat times.md
            printf "\n## Versions\n"
            printf "grep: "
            grep -V | head -n 1
            printf "ripgrep: "
            rg -V | head -n 1
            printf "node: "
            node --version | head -n 1
            printf "rustc: "
            rustc --version | head -n 1
            printf "go: "
            go version | head -n 1
            printf "cc: "
            cc --version | head -n 1
            printf "\n## Sample Data \n```"
            ls -l raw.tar
            printf "```\n"
          } >> "$GITHUB_STEP_SUMMARY"
